Linkanized/Controllers/MainCategoryController.cs
using Linkanized.Data;
using Linkanized.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace Linkanized.Controllers
{
    public class MainCategoryController : Controller
    {
        private readonly ApplicationDbContext _db;

        [BindProperty]
        public MainCategoryModel Category { get; set; }

        public MainCategoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> MainPanel()
        {
            var categories = await _db.MainCategories.ToListAsync();
            return View(categories);
        }

        public IActionResult Create()
        {
            Category = new MainCategoryModel();
            return View(Category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Save()
        {
            if (false == ModelState.IsValid)
                return View(Category);

            _db.MainCategories.Add(Category);
            _db.SaveChanges();

            return RedirectToAction("ListPanel");
        }
    }
}

Linkanized/Controllers/SubCategoryController.cs
using Linkanized.Data;
using Linkanized.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace Linkanized.Controllers
{
    public class SubCategoryController : Controller
    {
        private readonly ApplicationDbContext _db;

        public SubCategoryModel Category { get; set; }

        public SubCategoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> SubPanel(int id)
        {
            var categories = await _db.SubCategories
                .Where(c => c.MainCategoryId == id)
                .Include(c => c.MainCategory)
                .ToListAsync();

            return View(categories);
        }

        public IActionResult Create()
        {
            Category = new SubCategoryModel();
            return View(Category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Save()
        {
            if (false == ModelState.IsValid)
                return View(Category);

            _db.SubCategories.Add(Category);
            _db.SaveChanges();

            return RedirectToAction("ListPanel");
        }
    }
}

Linkanized/Views/MainCategory/Create.cshtml
@model Linkanized.Models.MainCategoryModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>MainCategoryModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" asp-action="Save" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ListPanel">Back to List</a>
</div>

Linkanized/Views/MainCategory/ListPanel.cshtml
@model IEnumerable<Linkanized.Models.MainCategoryModel>
@{ ViewData["Title"] = "ListPanel"; }

<div class="container col-8">
    @foreach (var item in Model)
    {
<a asp-controller="SubCategory" asp-action="ListPanel" asp-route-id="@item.Id">
    <input type="button" value="@item.Name" class="btn btn-primary col-3" style="height: 120px; margin-bottom: 20px;" />
</a>}
</div>

Linkanized/Views/MainCategory/MainPanel.cshtml
@model IEnumerable<Linkanized.Models.MainCategoryModel>
@{ ViewData["Title"] = "ListPanel"; }

<div class="container col-8">
    @foreach (var item in Model)
    {
<a asp-controller="SubCategory" asp-action="SubPanel" asp-route-id="@item.Id">
    <input type="button" value="@item.Name" class="btn btn-primary col-3" style="height: 120px; margin-bottom: 20px;" />
</a>}
</div>