Linkanized/Controllers/MainCategoryController.cs
using Linkanized.Data;
using Linkanized.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace Linkanized.Controllers
{
    public class MainCategoryController : Controller
    {
        private readonly ApplicationDbContext _db;

        [BindProperty]
        public MainCategoryModel Category { get; set; }

        public MainCategoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> MainPanel()
        {
            var categories = await _db.MainCategories.ToListAsync();
            return View(categories);
        }

        public IActionResult Create()
        {
            Category = new MainCategoryModel();
            return View(Category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Save()
        {
            if (false == ModelState.IsValid)
                return View(Category);

            _db.MainCategories.Add(Category);
            _db.SaveChanges();

            return RedirectToAction("ListPanel");
        }
    }
}

Linkanized/Controllers/ResourcesController.cs
using Linkanized.Data;
using Linkanized.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Linkanized.Controllers
{
    public class ResourcesController : Controller
    {
        private readonly ApplicationDbContext _db;

        [BindProperty]
        public ResourceModel Resource { get; set; }

        public ResourcesController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> List(int? id)
        {
            List<ResourceModel> resources;
            if (id == null)
            {
                resources = await _db.Resources.Include(r => r.MainCategory)
                                                   .Include(r => r.SubCategory)
                                                   .ToListAsync();
            }
            else
            {
                resources = await _db.Resources.Where(r => r.SubCategoryId == id)
                                                   .Include(r => r.MainCategory)
                                                   .Include(r => r.SubCategory)
                                                   .ToListAsync();
            }

            return View(resources);
        }

        public IActionResult Create()
        {
            Resource = new ResourceModel();
            return View(Resource);
        }

        public async Task<IActionResult> Edit(int id)
        {
            Resource = await _db.Resources.FirstOrDefaultAsync(r => r.Id == id);
            return View("Create", Resource);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Save()
        {
            if (false == ModelState.IsValid)
                return View("Create");

            if (0 == Resource.Id)
                _db.Resources.Add(Resource);
            else
                _db.Resources.Update(Resource);

            _db.SaveChanges();
            return RedirectToAction("List", new { id = Resource.SubCategoryId });
        }
    }
}

Linkanized/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Linkanized</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="MainCategory" asp-action="MainPanel">Linkanized</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MainCategory" asp-action="MainPanel">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Resources" asp-action="List" asp-all-route-data=null>All Links</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MainCategory" asp-action="Create">New Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Resources" asp-action="Create">New Link</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Linkanized - Created by Marcin Wawer
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>